swagger: '2.0'
info:
  title: Hotel Search Service
  description: Find, filter, sort and paginate hotels.
  version: "0.0.1"
  x-service-role: HOTSEARCH
# path used for API versioning
basePath: /v1
schemes:
  - http
produces:
  - application/json
      
paths:
  /hotelSearch/geoAccommodations:
    post:
      description: Get accommodations for given geo and categories
      operationId: getGeoAccommodations
      parameters:
        - name: hotelGeoRequest
          in: body
          schema:
            properties:
              geoId:
                description: The geo to search
                required: true
                type: integer
                format: int32
              locale:
                default: en_US
                type: string
              filters:
                $ref: '#/definitions/HotelFilters'
              pricingOptions:
                description: Options related to the format of the price to retrieve. Used in both pre and post date
                $ref: '#/definitions/PricingOptions'
              datedSearchOptions:
                description: Options related to dated search. Used only when we have dates to query with
                $ref: '#/definitions/DatedSearchOptions'
              page:
                $ref: '#/definitions/Page'
              sortOrder:
                description: The result sort order of accommodations, will use POP_RANK if not specified.
                $ref: '#/definitions/SortOrder'
              totalPollTime:
                description: |
                  Polling time in ms, i.e. time between the current and the first geoAccommodations call that was made
                  by client.
                default: 0
                type: integer
                format: int64
      responses:
        200:
          description: Filtered, sorted and paginated location ids together with the %% of the computation completion.
          schema:
            $ref: '#/definitions/HotelSearchResult'
  /hotelSearch/proximityAccommodations:
    post:
      description: |
        Get accommodations within a specific radius and optionally within a
        bounding box. Default sort is distance, tie-broken by pop index,
        tie-broken by localized alphabetical
      operationId: getProximityAccommodations
      parameters:
        - name: hotelProximityRequest
          in: body
          description: The proximity search information
          required: true
          schema:
            properties:
              centerLongitude:
                description: Used in conjunction with centerLatitude to define the center point to search from
                required: true
                type: number
                format: float
              centerLatitude:
                description: Used in conjunction with centerLongitude to define the center point to search from
                required: true
                type: number
                format: float
              radius:
                description: The radius (in mi) to search within
                required: true
                type: number
                format: float
                minimum: 0
                maximum: 32
              boundingBox:
                description: An optional bounding box for results
                $ref: '#/definitions/HotelBoundingBox'
              locale:
                default: en_US
                type: string
              accurateGeocodesOnly:
                description: Ignore low-quality location geo-codes
                default: false
                type: boolean
              filters:
                $ref: '#/definitions/HotelFilters'
              pricingOptions:
                description: Options related to the format of the price to retrieve. Used in both pre and post date
                $ref: '#/definitions/PricingOptions'
              datedSearchOptions:
                description: Options related to dated search. Used only when we have dates to query with
                $ref: '#/definitions/DatedSearchOptions'
              page:
                required: true
                $ref: '#/definitions/Page'
              sortOrder:
                description: |
                  The result sort order of accommodations, will use proximity from the centerLatitude /
                  centerLongitude if not specified.
                $ref: '#/definitions/SortOrder'
              totalPollTime:
                description: |
                  Polling time in ms, i.e. time between the current and the first proximityAccommodations call that was
                  made by client.
                default: 0
                type: integer
                format: int64
      responses:
        200:
          description: Filtered, sorted and paginated location ids together with the %% of the computation completion.
          schema:
            $ref: '#/definitions/HotelSearchResult'
  /hotelSearch/count:
    post:
      description: Get counts of accommodations for filter options
      operationId: count
      parameters:
        - name: countRequest
          in: body
          required: true
          schema:
            properties:
              locationIds:
                description: The list of location IDs for which to count across filter options
                required: true
                type: array
                items:
                  type: integer
                  format: int32
              filters:
                description: List of filter selections we have in place
                required: true
                $ref: '#/definitions/HotelFilters'
              filtersToCount:
                description: The list of filters to count with
                required: true
                type: array
                items:
                  $ref: '#/definitions/HotelSearchFilterType'
              locale:
                default: en_US
                type: string
              pricingOptions:
                description: Options related to the format of the price to retrieve. Used in both pre and post date
                required: false
                $ref: '#/definitions/PricingOptions'
              datedSearchOptions:
                description: Options related to dated search. Used only when we have dates to query with
                required: false
                $ref: '#/definitions/DatedSearchOptions'
              totalPollTime:
                description: |
                  Polling time in ms, i.e. time between the current and the first count call that was made
                  by client.
                default: 0
                type: integer
                format: int64
      responses:
        200:
          description: Nested maps of filter names to filter options to counts
          schema:
            $ref: '#/definitions/HotelCounts'
definitions:
  Page:
    type: object
    properties:
      offset:
        default: 0
        type: integer
        format: int32
      limit:
        default: 0
        type: integer
        format: int32
  SortOrder:
    type: string
    enum:
      - POP_RANK
      - PRICE_LOW_TO_HI
      - PRICE_HI_TO_LOW
  HotelSearchCategory:
    type: string
    enum:
      - UNKNOWN
      - HOTEL
      - BB
      - OTHER
      - VR
      - COLLAPSED_BB_INN
      
  HotelSearchClass:
    type: string
    enum:
      - ALL
      - 1_STAR
      - 1_5_STAR
      - 2_STAR
      - 2_5_STAR
      - 3_STAR
      - 3_5_STAR
      - 4_STAR
      - 4_5_STAR
      - 5_STAR
      
  HotelSearchRating:
    type: string
    enum:
      - ALL
      - ONE
      - TWO
      - THREE
      - FOUR
      - FIVE
  HotelSearchStyle:
    type: string
    enum:
      - ALL
      - BEACH
      - BUSINESS
      - CAMPGROUND
      - CAPSULE_HOTEL
      - CASINO
      - CASTLE
      - CONDO
      - COTTAGE
      - FAMILY
      - FARMHOUSE
      - GOVERNMENT_RESORT
      - GREEN
      - HOSTEL
      - JAPANESE_GUEST_HOUSE
      - KIBBUTZ
      - LODGE
      - LUXURY
      - ONSEN
      - RANCH
      - RESORT
      - ROMANTIC
      - RUSSIAN_HEALTH_RESORT
      - RUSSIAN_PENSION
      - RYOKAN
      - SKI_IN_OUT
      - SPA
      - TEMPLE_LODGING
      - TOURIST_BASE
      - VALUE
      - VILLA
  HotelSearchAmenities:
    type: string
    enum: &amenities
      - ADULT_POOL
      - AIRPORT_TRANSPORTATION
      - AIR_CONDITIONING
      - ALL_INCLUSIVE
      - BABY_SITTING_SERVICE
      - BANQUET_ROOM
      - BAR_LOUNGE
      - BEACH
      - BREAKFAST_AVAILABLE
      - BUSINESS_CENTER
      - CASINO
      - CONCIERGE_DESK
      - CONFERENCE_FACILITIES
      - DRY_CLEANING
      - FAMILY_ROOMS
      - FITNESS_CENTER
      - FREE_AIRPORT_SHUTTLE
      - FREE_BREAKFAST
      - FREE_INTERNET
      - FREE_PARKING
      - GOLF
      - HEATED_POOL
      - HOT_TUB
      - INDOOR_POOL
      - KIDS_ACTIVITIES
      - KIDS_POOL
      - KITCHENETTE
      - LAUNDRY
      - MEETING_ROOM
      - MICROWAVE
      - MINIBAR
      - MULTILINGUAL_STAFF
      - NON_SMOKING
      - NON_SMOKING_HOTEL
      - OUTDOOR_POOL
      - PETS_ALLOWED
      - REDUCED_MOBILITY_ROOMS
      - REFRIGERATOR
      - RESTAURANT
      - ROOM_SERVICE
      - SELF_SERVICE_LAUNDRY_FACILITIES
      - SHUTTLE
      - SKI_IN_OUT
      - SPA
      - SMOKING_ROOMS
      - SUITES
      - SWIMMING_POOL
      - TENNIS_COURT
      - TV_CHANNEL_ONE_RUSSIA
      - TV_NTV_WORLD_RUSSIA
      - TV_OTHER_RUSSIA
      - TV_RTR_PLANETA_RUSSIA
      - WHEELCHAIR_ACCESS
      - WIRELESS_INTERNET_IN_PUBLIC_AREAS
  HotelSearchFilterType:
    type: string
    enum:
      - HOTEL_CATEGORY
      - HOTEL_CLASS
      - AMENITY
      - TRAVELER_STYLE
      - TRAVELER_RATING
      - SEARCH_RADIUS
      - PRICE_RANGE
      # Deprecated, use PRICE_RANGE instead
      - HAC_PRICE_RANGE
      # Deprecated, use PRICE_RANGE instead
      - HISTORIC_PRICE_RANGE
  HotelSearchPriceRangeData:
    type: object
    properties:
      priceRangeCounts:
        description: A list of price range counts for each price range index
        type: array
        items:
          type: integer
          format: int32
      priceRanges:
        description: |
          A list of price range threshold prices for each price range counted by priceRangeCounts.
          For example, [250, 300, 450] will be interpreted as [0, 250), [250, 300), [300, 450),
          [450, infinity)
        type: array
        items:
          type: integer
          format: int32
  HotelFilters:
    type: object
    properties:
      accommodationCategories:
        type: array
        items:
          $ref: '#/definitions/HotelSearchCategory'
      amenities:
        type: array
        items:
          $ref: '#/definitions/HotelSearchAmenities'
      hotelClass:
        type: array
        items:
          $ref: '#/definitions/HotelSearchClass'
      rating:
        type: array
        items:
          $ref: '#/definitions/HotelSearchRating'
      travelStyle:
        type: array
        items:
          $ref: '#/definitions/HotelSearchStyle'
      priceRangesFilter:
        $ref: '#/definitions/HotelPriceRangeFilter'
      distance:
        $ref: '#/definitions/HotelDistanceFilter'
  HotelPriceRangeFilter:
    type: object
    properties:
      priceRanges:
        description: List of price range indices on which we would like to filter locations by their price ranges
        type: array
        items:
          type: integer
          format: int32
      filterWithHistoricPrices:
        deprecated: true
        description: This field is ignored and can be removed after the roll-out of HOT-10532
        type: boolean
        default: false
  HotelDistanceFilter:
    type: object
    properties:
      centerLongitude:
        description: Used in conjunction with centerLatitude to define the center point to measure distance from
        required: true
        type: number
        format: float
      centerLatitude:
        description: Used in conjunction with centerLongitude to define the center point to measure distance from
        required: true
        type: number
        format: float
      accurateGeocodesOnly:
        description: Ignore low-quality location geo-codes
        default: false
        type: boolean
      useMiles:
        description: True if miles should be used, kilometer otherwise
        type: boolean
        default: true
      radii:
        description: Radius to search within
        type: array
        items:
          type: integer
          format: int32
  HotelBoundingBox:
    type: object
    properties:
      minLongitude:
        description: |
          Part of the four min/max longitudes/latitudes that together define the
          optional bounding rectangle in which to filter
        type: number